/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.metaTemplating.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.metaTemplating.MetaPh;
import org.xtext.example.mydsl.metaTemplating.MetaTemplatingPackage;
import org.xtext.example.mydsl.metaTemplating.Parameter;
import org.xtext.example.mydsl.metaTemplating.SubQuery;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sub Query</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl#getMethItem <em>Meth Item</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl#getMethRef <em>Meth Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl#getItem <em>Item</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubQueryImpl extends MinimalEObjectImpl.Container implements SubQuery
{
  /**
   * The default value of the '{@link #getMethItem() <em>Meth Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethItem()
   * @generated
   * @ordered
   */
  protected static final String METH_ITEM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMethItem() <em>Meth Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethItem()
   * @generated
   * @ordered
   */
  protected String methItem = METH_ITEM_EDEFAULT;

  /**
   * The cached value of the '{@link #getMethRef() <em>Meth Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethRef()
   * @generated
   * @ordered
   */
  protected MetaPh methRef;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected Parameter params;

  /**
   * The default value of the '{@link #getItem() <em>Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItem()
   * @generated
   * @ordered
   */
  protected static final String ITEM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getItem() <em>Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItem()
   * @generated
   * @ordered
   */
  protected String item = ITEM_EDEFAULT;

  /**
   * The cached value of the '{@link #getRef() <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected MetaPh ref;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubQueryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaTemplatingPackage.Literals.SUB_QUERY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMethItem()
  {
    return methItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMethItem(String newMethItem)
  {
    String oldMethItem = methItem;
    methItem = newMethItem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__METH_ITEM, oldMethItem, methItem));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MetaPh getMethRef()
  {
    return methRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMethRef(MetaPh newMethRef, NotificationChain msgs)
  {
    MetaPh oldMethRef = methRef;
    methRef = newMethRef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__METH_REF, oldMethRef, newMethRef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMethRef(MetaPh newMethRef)
  {
    if (newMethRef != methRef)
    {
      NotificationChain msgs = null;
      if (methRef != null)
        msgs = ((InternalEObject)methRef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__METH_REF, null, msgs);
      if (newMethRef != null)
        msgs = ((InternalEObject)newMethRef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__METH_REF, null, msgs);
      msgs = basicSetMethRef(newMethRef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__METH_REF, newMethRef, newMethRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parameter getParams()
  {
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParams(Parameter newParams, NotificationChain msgs)
  {
    Parameter oldParams = params;
    params = newParams;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__PARAMS, oldParams, newParams);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParams(Parameter newParams)
  {
    if (newParams != params)
    {
      NotificationChain msgs = null;
      if (params != null)
        msgs = ((InternalEObject)params).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__PARAMS, null, msgs);
      if (newParams != null)
        msgs = ((InternalEObject)newParams).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__PARAMS, null, msgs);
      msgs = basicSetParams(newParams, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__PARAMS, newParams, newParams));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getItem()
  {
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItem(String newItem)
  {
    String oldItem = item;
    item = newItem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__ITEM, oldItem, item));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MetaPh getRef()
  {
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRef(MetaPh newRef, NotificationChain msgs)
  {
    MetaPh oldRef = ref;
    ref = newRef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__REF, oldRef, newRef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRef(MetaPh newRef)
  {
    if (newRef != ref)
    {
      NotificationChain msgs = null;
      if (ref != null)
        msgs = ((InternalEObject)ref).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__REF, null, msgs);
      if (newRef != null)
        msgs = ((InternalEObject)newRef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaTemplatingPackage.SUB_QUERY__REF, null, msgs);
      msgs = basicSetRef(newRef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaTemplatingPackage.SUB_QUERY__REF, newRef, newRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaTemplatingPackage.SUB_QUERY__METH_REF:
        return basicSetMethRef(null, msgs);
      case MetaTemplatingPackage.SUB_QUERY__PARAMS:
        return basicSetParams(null, msgs);
      case MetaTemplatingPackage.SUB_QUERY__REF:
        return basicSetRef(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaTemplatingPackage.SUB_QUERY__METH_ITEM:
        return getMethItem();
      case MetaTemplatingPackage.SUB_QUERY__METH_REF:
        return getMethRef();
      case MetaTemplatingPackage.SUB_QUERY__PARAMS:
        return getParams();
      case MetaTemplatingPackage.SUB_QUERY__ITEM:
        return getItem();
      case MetaTemplatingPackage.SUB_QUERY__REF:
        return getRef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaTemplatingPackage.SUB_QUERY__METH_ITEM:
        setMethItem((String)newValue);
        return;
      case MetaTemplatingPackage.SUB_QUERY__METH_REF:
        setMethRef((MetaPh)newValue);
        return;
      case MetaTemplatingPackage.SUB_QUERY__PARAMS:
        setParams((Parameter)newValue);
        return;
      case MetaTemplatingPackage.SUB_QUERY__ITEM:
        setItem((String)newValue);
        return;
      case MetaTemplatingPackage.SUB_QUERY__REF:
        setRef((MetaPh)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaTemplatingPackage.SUB_QUERY__METH_ITEM:
        setMethItem(METH_ITEM_EDEFAULT);
        return;
      case MetaTemplatingPackage.SUB_QUERY__METH_REF:
        setMethRef((MetaPh)null);
        return;
      case MetaTemplatingPackage.SUB_QUERY__PARAMS:
        setParams((Parameter)null);
        return;
      case MetaTemplatingPackage.SUB_QUERY__ITEM:
        setItem(ITEM_EDEFAULT);
        return;
      case MetaTemplatingPackage.SUB_QUERY__REF:
        setRef((MetaPh)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaTemplatingPackage.SUB_QUERY__METH_ITEM:
        return METH_ITEM_EDEFAULT == null ? methItem != null : !METH_ITEM_EDEFAULT.equals(methItem);
      case MetaTemplatingPackage.SUB_QUERY__METH_REF:
        return methRef != null;
      case MetaTemplatingPackage.SUB_QUERY__PARAMS:
        return params != null;
      case MetaTemplatingPackage.SUB_QUERY__ITEM:
        return ITEM_EDEFAULT == null ? item != null : !ITEM_EDEFAULT.equals(item);
      case MetaTemplatingPackage.SUB_QUERY__REF:
        return ref != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (methItem: ");
    result.append(methItem);
    result.append(", item: ");
    result.append(item);
    result.append(')');
    return result.toString();
  }

} //SubQueryImpl
