/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.metatemplating.ui.internal.MetatemplatingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MetaTemplatingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MetatemplatingActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MetatemplatingActivator activator = MetatemplatingActivator.getInstance();
		return activator != null ? activator.getInjector(MetatemplatingActivator.ORG_XTEXT_EXAMPLE_MYDSL_METATEMPLATING) : null;
	}

}
