/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.metaTemplating;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.metaTemplating.MetaTemplatingFactory
 * @model kind="package"
 * @generated
 */
public interface MetaTemplatingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "metaTemplating";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MetaTemplating";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "metaTemplating";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MetaTemplatingPackage eINSTANCE = org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.ModelImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__HEADER = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTENT = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.HeaderImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 1;

  /**
   * The feature id for the '<em><b>Libs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__LIBS = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__IMPORTS = 1;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.ImportImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__PATH = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.LibrariesImpl <em>Libraries</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.LibrariesImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getLibraries()
   * @generated
   */
  int LIBRARIES = 3;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARIES__PATH = 0;

  /**
   * The number of structural features of the '<em>Libraries</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.NoteImpl <em>Note</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.NoteImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getNote()
   * @generated
   */
  int NOTE = 4;

  /**
   * The feature id for the '<em><b>Word</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE__WORD = 0;

  /**
   * The number of structural features of the '<em>Note</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.InstructionsImpl <em>Instructions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.InstructionsImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getInstructions()
   * @generated
   */
  int INSTRUCTIONS = 5;

  /**
   * The feature id for the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__NOTE = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__FILTER = 2;

  /**
   * The feature id for the '<em><b>Meta Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__META_FILTER = 3;

  /**
   * The feature id for the '<em><b>Iterator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__ITERATOR = 4;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS__RULE = 5;

  /**
   * The number of structural features of the '<em>Instructions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTIONS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.StatementImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__TEXT = 0;

  /**
   * The feature id for the '<em><b>Char</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__CHAR = 1;

  /**
   * The feature id for the '<em><b>String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__STRING = 2;

  /**
   * The feature id for the '<em><b>Inject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__INJECT = 3;

  /**
   * The feature id for the '<em><b>Meta Inject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__META_INJECT = 4;

  /**
   * The feature id for the '<em><b>Placeholder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__PLACEHOLDER = 5;

  /**
   * The feature id for the '<em><b>Meta Placeholder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__META_PLACEHOLDER = 6;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaFilterImpl <em>Meta Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaFilterImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaFilter()
   * @generated
   */
  int META_FILTER = 7;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_FILTER__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Truebody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_FILTER__TRUEBODY = 1;

  /**
   * The feature id for the '<em><b>Falsebody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_FILTER__FALSEBODY = 2;

  /**
   * The number of structural features of the '<em>Meta Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_FILTER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.FilterImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 8;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Truebody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__TRUEBODY = 1;

  /**
   * The feature id for the '<em><b>Falsebody</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__FALSEBODY = 2;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.RuleImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getRule()
   * @generated
   */
  int RULE = 9;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__PROPERTY = 1;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__TAG = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__BODY = 3;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.PropertyImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 10;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__PROPERTY = 0;

  /**
   * The feature id for the '<em><b>Sub Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__SUB_PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubPropertyImpl <em>Sub Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.SubPropertyImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubProperty()
   * @generated
   */
  int SUB_PROPERTY = 11;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROPERTY__METHOD = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROPERTY__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROPERTY__PROPERTY = 2;

  /**
   * The number of structural features of the '<em>Sub Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROPERTY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.IteratorImpl <em>Iterator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.IteratorImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getIterator()
   * @generated
   */
  int ITERATOR = 12;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITERATOR__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITERATOR__QUERY = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITERATOR__BODY = 2;

  /**
   * The number of structural features of the '<em>Iterator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITERATOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.QueryImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 13;

  /**
   * The feature id for the '<em><b>Item</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__ITEM = 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__REF = 1;

  /**
   * The feature id for the '<em><b>Sub Query</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__SUB_QUERY = 2;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl <em>Sub Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubQuery()
   * @generated
   */
  int SUB_QUERY = 14;

  /**
   * The feature id for the '<em><b>Meth Item</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY__METH_ITEM = 0;

  /**
   * The feature id for the '<em><b>Meth Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY__METH_REF = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Item</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY__ITEM = 3;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY__REF = 4;

  /**
   * The number of structural features of the '<em>Sub Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_QUERY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhImpl <em>Ph</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.PhImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPh()
   * @generated
   */
  int PH = 15;

  /**
   * The feature id for the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH__PROPERTY = 0;

  /**
   * The number of structural features of the '<em>Ph</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaPhImpl <em>Meta Ph</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaPhImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaPh()
   * @generated
   */
  int META_PH = 16;

  /**
   * The feature id for the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_PH__PROPERTY = 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_PH__TAG = 1;

  /**
   * The number of structural features of the '<em>Meta Ph</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_PH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhPropertyImpl <em>Ph Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.PhPropertyImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPhProperty()
   * @generated
   */
  int PH_PROPERTY = 17;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_PROPERTY__PROPERTY = 0;

  /**
   * The feature id for the '<em><b>Sub Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_PROPERTY__SUB_PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Ph Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhSubPropertyImpl <em>Ph Sub Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.PhSubPropertyImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPhSubProperty()
   * @generated
   */
  int PH_SUB_PROPERTY = 18;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_SUB_PROPERTY__METHOD = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_SUB_PROPERTY__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_SUB_PROPERTY__PROPERTY = 2;

  /**
   * The feature id for the '<em><b>Meta Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_SUB_PROPERTY__META_PROPERTY = 3;

  /**
   * The number of structural features of the '<em>Ph Sub Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PH_SUB_PROPERTY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.ParameterImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 19;

  /**
   * The feature id for the '<em><b>Par</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PAR = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubParameterImpl <em>Sub Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.SubParameterImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubParameter()
   * @generated
   */
  int SUB_PARAMETER = 20;

  /**
   * The feature id for the '<em><b>Par</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PARAMETER__PAR = 0;

  /**
   * The number of structural features of the '<em>Sub Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.InjectImpl <em>Inject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.InjectImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getInject()
   * @generated
   */
  int INJECT = 21;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INJECT__CODE = 0;

  /**
   * The number of structural features of the '<em>Inject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaInjectImpl <em>Meta Inject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaInjectImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaInject()
   * @generated
   */
  int META_INJECT = 22;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INJECT__CODE = 0;

  /**
   * The number of structural features of the '<em>Meta Inject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.EscapedStringImpl <em>Escaped String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.EscapedStringImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getEscapedString()
   * @generated
   */
  int ESCAPED_STRING = 23;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCAPED_STRING__STR = 0;

  /**
   * The number of structural features of the '<em>Escaped String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCAPED_STRING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.metaTemplating.impl.EscapedImpl <em>Escaped</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.metaTemplating.impl.EscapedImpl
   * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getEscaped()
   * @generated
   */
  int ESCAPED = 24;

  /**
   * The feature id for the '<em><b>Char</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCAPED__CHAR = 0;

  /**
   * The number of structural features of the '<em>Escaped</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCAPED_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Model#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Model#getHeader()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Header();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Model#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Content</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Model#getContent()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Header#getLibs <em>Libs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Libs</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Header#getLibs()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_Libs();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Header#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Header#getImports()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_Imports();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Import#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Import#getPath()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Libraries <em>Libraries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Libraries</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Libraries
   * @generated
   */
  EClass getLibraries();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Libraries#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Libraries#getPath()
   * @see #getLibraries()
   * @generated
   */
  EAttribute getLibraries_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Note <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Note</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Note
   * @generated
   */
  EClass getNote();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.metaTemplating.Note#getWord <em>Word</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Word</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Note#getWord()
   * @see #getNote()
   * @generated
   */
  EAttribute getNote_Word();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Instructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instructions</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions
   * @generated
   */
  EClass getInstructions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getNote <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Note</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getNote()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_Note();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getStatement()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_Statement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getFilter()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_Filter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getMetaFilter <em>Meta Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Filter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getMetaFilter()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_MetaFilter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getIterator <em>Iterator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Iterator</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getIterator()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_Iterator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Instructions#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Instructions#getRule()
   * @see #getInstructions()
   * @generated
   */
  EReference getInstructions_Rule();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Statement#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getText()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getChar <em>Char</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Char</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getChar()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Char();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>String</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getString()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_String();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getInject <em>Inject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inject</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getInject()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Inject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getMetaInject <em>Meta Inject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Inject</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getMetaInject()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_MetaInject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getPlaceholder <em>Placeholder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Placeholder</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getPlaceholder()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Placeholder();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Statement#getMetaPlaceholder <em>Meta Placeholder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Placeholder</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Statement#getMetaPlaceholder()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_MetaPlaceholder();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.MetaFilter <em>Meta Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meta Filter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaFilter
   * @generated
   */
  EClass getMetaFilter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.MetaFilter#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaFilter#getCondition()
   * @see #getMetaFilter()
   * @generated
   */
  EReference getMetaFilter_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.MetaFilter#getTruebody <em>Truebody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Truebody</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaFilter#getTruebody()
   * @see #getMetaFilter()
   * @generated
   */
  EReference getMetaFilter_Truebody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.MetaFilter#getFalsebody <em>Falsebody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Falsebody</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaFilter#getFalsebody()
   * @see #getMetaFilter()
   * @generated
   */
  EReference getMetaFilter_Falsebody();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Filter#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Filter#getCondition()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Filter#getTruebody <em>Truebody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Truebody</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Filter#getTruebody()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Truebody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Filter#getFalsebody <em>Falsebody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Falsebody</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Filter#getFalsebody()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Falsebody();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Rule#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Rule#getElement()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Element();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Rule#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Rule#getProperty()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Property();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Rule#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Rule#getTag()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Tag();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Rule#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Rule#getBody()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Property#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Property#getProperty()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Property();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Property#getSubProperties <em>Sub Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Properties</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Property#getSubProperties()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_SubProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.SubProperty <em>Sub Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubProperty
   * @generated
   */
  EClass getSubProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.SubProperty#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubProperty#getMethod()
   * @see #getSubProperty()
   * @generated
   */
  EAttribute getSubProperty_Method();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.SubProperty#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Params</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubProperty#getParams()
   * @see #getSubProperty()
   * @generated
   */
  EReference getSubProperty_Params();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.SubProperty#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubProperty#getProperty()
   * @see #getSubProperty()
   * @generated
   */
  EAttribute getSubProperty_Property();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Iterator <em>Iterator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Iterator</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Iterator
   * @generated
   */
  EClass getIterator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Iterator#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Iterator#getElement()
   * @see #getIterator()
   * @generated
   */
  EAttribute getIterator_Element();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Iterator#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Iterator#getQuery()
   * @see #getIterator()
   * @generated
   */
  EReference getIterator_Query();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Iterator#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Iterator#getBody()
   * @see #getIterator()
   * @generated
   */
  EReference getIterator_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Query#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Item</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Query#getItem()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Item();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Query#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Query#getRef()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Ref();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Query#getSubQuery <em>Sub Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Query</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Query#getSubQuery()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_SubQuery();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.SubQuery <em>Sub Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Query</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery
   * @generated
   */
  EClass getSubQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.SubQuery#getMethItem <em>Meth Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Meth Item</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery#getMethItem()
   * @see #getSubQuery()
   * @generated
   */
  EAttribute getSubQuery_MethItem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.SubQuery#getMethRef <em>Meth Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meth Ref</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery#getMethRef()
   * @see #getSubQuery()
   * @generated
   */
  EReference getSubQuery_MethRef();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.SubQuery#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Params</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery#getParams()
   * @see #getSubQuery()
   * @generated
   */
  EReference getSubQuery_Params();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.SubQuery#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Item</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery#getItem()
   * @see #getSubQuery()
   * @generated
   */
  EAttribute getSubQuery_Item();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.SubQuery#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubQuery#getRef()
   * @see #getSubQuery()
   * @generated
   */
  EReference getSubQuery_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Ph <em>Ph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ph</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Ph
   * @generated
   */
  EClass getPh();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.Ph#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Ph#getProperty()
   * @see #getPh()
   * @generated
   */
  EReference getPh_Property();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.MetaPh <em>Meta Ph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meta Ph</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaPh
   * @generated
   */
  EClass getMetaPh();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.MetaPh#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaPh#getProperty()
   * @see #getMetaPh()
   * @generated
   */
  EReference getMetaPh_Property();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.MetaPh#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaPh#getTag()
   * @see #getMetaPh()
   * @generated
   */
  EAttribute getMetaPh_Tag();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.PhProperty <em>Ph Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ph Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhProperty
   * @generated
   */
  EClass getPhProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.PhProperty#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhProperty#getProperty()
   * @see #getPhProperty()
   * @generated
   */
  EAttribute getPhProperty_Property();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.PhProperty#getSubProperties <em>Sub Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Properties</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhProperty#getSubProperties()
   * @see #getPhProperty()
   * @generated
   */
  EReference getPhProperty_SubProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.PhSubProperty <em>Ph Sub Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ph Sub Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhSubProperty
   * @generated
   */
  EClass getPhSubProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.PhSubProperty#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhSubProperty#getMethod()
   * @see #getPhSubProperty()
   * @generated
   */
  EAttribute getPhSubProperty_Method();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.PhSubProperty#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Params</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhSubProperty#getParams()
   * @see #getPhSubProperty()
   * @generated
   */
  EReference getPhSubProperty_Params();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.PhSubProperty#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhSubProperty#getProperty()
   * @see #getPhSubProperty()
   * @generated
   */
  EAttribute getPhSubProperty_Property();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.metaTemplating.PhSubProperty#getMetaProperty <em>Meta Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Property</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.PhSubProperty#getMetaProperty()
   * @see #getPhSubProperty()
   * @generated
   */
  EReference getPhSubProperty_MetaProperty();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Parameter#getPar <em>Par</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Par</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Parameter#getPar()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Par();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.metaTemplating.Parameter#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Parameter#getParams()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.SubParameter <em>Sub Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Parameter</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubParameter
   * @generated
   */
  EClass getSubParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.SubParameter#getPar <em>Par</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Par</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.SubParameter#getPar()
   * @see #getSubParameter()
   * @generated
   */
  EAttribute getSubParameter_Par();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Inject <em>Inject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inject</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Inject
   * @generated
   */
  EClass getInject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Inject#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Inject#getCode()
   * @see #getInject()
   * @generated
   */
  EAttribute getInject_Code();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.MetaInject <em>Meta Inject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meta Inject</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaInject
   * @generated
   */
  EClass getMetaInject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.MetaInject#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.MetaInject#getCode()
   * @see #getMetaInject()
   * @generated
   */
  EAttribute getMetaInject_Code();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.EscapedString <em>Escaped String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Escaped String</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.EscapedString
   * @generated
   */
  EClass getEscapedString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.EscapedString#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.EscapedString#getStr()
   * @see #getEscapedString()
   * @generated
   */
  EAttribute getEscapedString_Str();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.metaTemplating.Escaped <em>Escaped</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Escaped</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Escaped
   * @generated
   */
  EClass getEscaped();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.metaTemplating.Escaped#getChar <em>Char</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Char</em>'.
   * @see org.xtext.example.mydsl.metaTemplating.Escaped#getChar()
   * @see #getEscaped()
   * @generated
   */
  EAttribute getEscaped_Char();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MetaTemplatingFactory getMetaTemplatingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.ModelImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__HEADER = eINSTANCE.getModel_Header();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONTENT = eINSTANCE.getModel_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.HeaderImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Libs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__LIBS = eINSTANCE.getHeader_Libs();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__IMPORTS = eINSTANCE.getHeader_Imports();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.ImportImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__PATH = eINSTANCE.getImport_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.LibrariesImpl <em>Libraries</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.LibrariesImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getLibraries()
     * @generated
     */
    EClass LIBRARIES = eINSTANCE.getLibraries();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIBRARIES__PATH = eINSTANCE.getLibraries_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.NoteImpl <em>Note</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.NoteImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getNote()
     * @generated
     */
    EClass NOTE = eINSTANCE.getNote();

    /**
     * The meta object literal for the '<em><b>Word</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTE__WORD = eINSTANCE.getNote_Word();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.InstructionsImpl <em>Instructions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.InstructionsImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getInstructions()
     * @generated
     */
    EClass INSTRUCTIONS = eINSTANCE.getInstructions();

    /**
     * The meta object literal for the '<em><b>Note</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__NOTE = eINSTANCE.getInstructions_Note();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__STATEMENT = eINSTANCE.getInstructions_Statement();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__FILTER = eINSTANCE.getInstructions_Filter();

    /**
     * The meta object literal for the '<em><b>Meta Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__META_FILTER = eINSTANCE.getInstructions_MetaFilter();

    /**
     * The meta object literal for the '<em><b>Iterator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__ITERATOR = eINSTANCE.getInstructions_Iterator();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTIONS__RULE = eINSTANCE.getInstructions_Rule();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.StatementImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__TEXT = eINSTANCE.getStatement_Text();

    /**
     * The meta object literal for the '<em><b>Char</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__CHAR = eINSTANCE.getStatement_Char();

    /**
     * The meta object literal for the '<em><b>String</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__STRING = eINSTANCE.getStatement_String();

    /**
     * The meta object literal for the '<em><b>Inject</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__INJECT = eINSTANCE.getStatement_Inject();

    /**
     * The meta object literal for the '<em><b>Meta Inject</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__META_INJECT = eINSTANCE.getStatement_MetaInject();

    /**
     * The meta object literal for the '<em><b>Placeholder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__PLACEHOLDER = eINSTANCE.getStatement_Placeholder();

    /**
     * The meta object literal for the '<em><b>Meta Placeholder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__META_PLACEHOLDER = eINSTANCE.getStatement_MetaPlaceholder();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaFilterImpl <em>Meta Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaFilterImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaFilter()
     * @generated
     */
    EClass META_FILTER = eINSTANCE.getMetaFilter();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference META_FILTER__CONDITION = eINSTANCE.getMetaFilter_Condition();

    /**
     * The meta object literal for the '<em><b>Truebody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference META_FILTER__TRUEBODY = eINSTANCE.getMetaFilter_Truebody();

    /**
     * The meta object literal for the '<em><b>Falsebody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference META_FILTER__FALSEBODY = eINSTANCE.getMetaFilter_Falsebody();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.FilterImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__CONDITION = eINSTANCE.getFilter_Condition();

    /**
     * The meta object literal for the '<em><b>Truebody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__TRUEBODY = eINSTANCE.getFilter_Truebody();

    /**
     * The meta object literal for the '<em><b>Falsebody</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__FALSEBODY = eINSTANCE.getFilter_Falsebody();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.RuleImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ELEMENT = eINSTANCE.getRule_Element();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__PROPERTY = eINSTANCE.getRule_Property();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__TAG = eINSTANCE.getRule_Tag();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__BODY = eINSTANCE.getRule_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.PropertyImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__PROPERTY = eINSTANCE.getProperty_Property();

    /**
     * The meta object literal for the '<em><b>Sub Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__SUB_PROPERTIES = eINSTANCE.getProperty_SubProperties();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubPropertyImpl <em>Sub Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.SubPropertyImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubProperty()
     * @generated
     */
    EClass SUB_PROPERTY = eINSTANCE.getSubProperty();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PROPERTY__METHOD = eINSTANCE.getSubProperty_Method();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_PROPERTY__PARAMS = eINSTANCE.getSubProperty_Params();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PROPERTY__PROPERTY = eINSTANCE.getSubProperty_Property();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.IteratorImpl <em>Iterator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.IteratorImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getIterator()
     * @generated
     */
    EClass ITERATOR = eINSTANCE.getIterator();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITERATOR__ELEMENT = eINSTANCE.getIterator_Element();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITERATOR__QUERY = eINSTANCE.getIterator_Query();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITERATOR__BODY = eINSTANCE.getIterator_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.QueryImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__ITEM = eINSTANCE.getQuery_Item();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__REF = eINSTANCE.getQuery_Ref();

    /**
     * The meta object literal for the '<em><b>Sub Query</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__SUB_QUERY = eINSTANCE.getQuery_SubQuery();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl <em>Sub Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.SubQueryImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubQuery()
     * @generated
     */
    EClass SUB_QUERY = eINSTANCE.getSubQuery();

    /**
     * The meta object literal for the '<em><b>Meth Item</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_QUERY__METH_ITEM = eINSTANCE.getSubQuery_MethItem();

    /**
     * The meta object literal for the '<em><b>Meth Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_QUERY__METH_REF = eINSTANCE.getSubQuery_MethRef();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_QUERY__PARAMS = eINSTANCE.getSubQuery_Params();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_QUERY__ITEM = eINSTANCE.getSubQuery_Item();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_QUERY__REF = eINSTANCE.getSubQuery_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhImpl <em>Ph</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.PhImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPh()
     * @generated
     */
    EClass PH = eINSTANCE.getPh();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PH__PROPERTY = eINSTANCE.getPh_Property();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaPhImpl <em>Meta Ph</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaPhImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaPh()
     * @generated
     */
    EClass META_PH = eINSTANCE.getMetaPh();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference META_PH__PROPERTY = eINSTANCE.getMetaPh_Property();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute META_PH__TAG = eINSTANCE.getMetaPh_Tag();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhPropertyImpl <em>Ph Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.PhPropertyImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPhProperty()
     * @generated
     */
    EClass PH_PROPERTY = eINSTANCE.getPhProperty();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PH_PROPERTY__PROPERTY = eINSTANCE.getPhProperty_Property();

    /**
     * The meta object literal for the '<em><b>Sub Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PH_PROPERTY__SUB_PROPERTIES = eINSTANCE.getPhProperty_SubProperties();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.PhSubPropertyImpl <em>Ph Sub Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.PhSubPropertyImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getPhSubProperty()
     * @generated
     */
    EClass PH_SUB_PROPERTY = eINSTANCE.getPhSubProperty();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PH_SUB_PROPERTY__METHOD = eINSTANCE.getPhSubProperty_Method();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PH_SUB_PROPERTY__PARAMS = eINSTANCE.getPhSubProperty_Params();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PH_SUB_PROPERTY__PROPERTY = eINSTANCE.getPhSubProperty_Property();

    /**
     * The meta object literal for the '<em><b>Meta Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PH_SUB_PROPERTY__META_PROPERTY = eINSTANCE.getPhSubProperty_MetaProperty();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.ParameterImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Par</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__PAR = eINSTANCE.getParameter_Par();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMS = eINSTANCE.getParameter_Params();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.SubParameterImpl <em>Sub Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.SubParameterImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getSubParameter()
     * @generated
     */
    EClass SUB_PARAMETER = eINSTANCE.getSubParameter();

    /**
     * The meta object literal for the '<em><b>Par</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PARAMETER__PAR = eINSTANCE.getSubParameter_Par();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.InjectImpl <em>Inject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.InjectImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getInject()
     * @generated
     */
    EClass INJECT = eINSTANCE.getInject();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INJECT__CODE = eINSTANCE.getInject_Code();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.MetaInjectImpl <em>Meta Inject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaInjectImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getMetaInject()
     * @generated
     */
    EClass META_INJECT = eINSTANCE.getMetaInject();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute META_INJECT__CODE = eINSTANCE.getMetaInject_Code();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.EscapedStringImpl <em>Escaped String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.EscapedStringImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getEscapedString()
     * @generated
     */
    EClass ESCAPED_STRING = eINSTANCE.getEscapedString();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESCAPED_STRING__STR = eINSTANCE.getEscapedString_Str();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.metaTemplating.impl.EscapedImpl <em>Escaped</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.metaTemplating.impl.EscapedImpl
     * @see org.xtext.example.mydsl.metaTemplating.impl.MetaTemplatingPackageImpl#getEscaped()
     * @generated
     */
    EClass ESCAPED = eINSTANCE.getEscaped();

    /**
     * The meta object literal for the '<em><b>Char</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESCAPED__CHAR = eINSTANCE.getEscaped_Char();

  }

} //MetaTemplatingPackage
